# Generated by Django 3.0.3 on 2021-12-09 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nav_dash', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
