# Generated by Django 3.1.2 on 2021-12-10 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nav_dash', '0002_delete_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='post',
            fields=[
                ('assistant_name', models.AutoField(primary_key=True, serialize=False)),
                ('primary_color', models.CharField(blank=True, max_length=200, null=True)),
                ('secondary_color', models.CharField(blank=True, max_length=200, null=True)),
                ('accent_color', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
