# Generated by Django 3.0.3 on 2021-12-11 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nav_dash', '0004_auto_20211211_1449'),
    ]

    operations = [
        migrations.DeleteModel(
            name='profile',
        ),
    ]
