# Generated by Django 3.0.3 on 2021-12-11 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nav_dash', '0008_auto_20211211_1544'),
    ]

    operations = [
        migrations.CreateModel(
            name='homescreen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('greetings', models.CharField(blank=True, max_length=200, null=True)),
                ('conv', models.CharField(blank=True, max_length=200, null=True)),
                ('button', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='suggestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('button', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='profile',
        ),
    ]
