# Generated by Django 3.1.2 on 2021-12-13 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nav_dash', '0010_suggestions_radio_support'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='profile_pic',
            field=models.ImageField(blank=True, default='image.jpg', null=True, upload_to=''),
        ),
    ]
